// <auto-generated />
using System;
using BudgetPlanner2Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BudgetPlanner2Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210316145351_SeedExpenses")]
    partial class SeedExpenses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BudgetPlanner2Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ExpenseId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            ExpenseId = 1337,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "0 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 993, DateTimeKind.Local).AddTicks(2587)
                        },
                        new
                        {
                            ExpenseId = 1338,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "1 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1032)
                        },
                        new
                        {
                            ExpenseId = 1339,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "2 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1317)
                        },
                        new
                        {
                            ExpenseId = 1340,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "3 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1376)
                        },
                        new
                        {
                            ExpenseId = 1341,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "4 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1424)
                        },
                        new
                        {
                            ExpenseId = 1342,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "5 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1484)
                        },
                        new
                        {
                            ExpenseId = 1343,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "6 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1533)
                        },
                        new
                        {
                            ExpenseId = 1344,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "7 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1580)
                        },
                        new
                        {
                            ExpenseId = 1345,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "8 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1623)
                        },
                        new
                        {
                            ExpenseId = 1346,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "9 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1672)
                        },
                        new
                        {
                            ExpenseId = 1347,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "10 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1722)
                        },
                        new
                        {
                            ExpenseId = 1348,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "11 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1765)
                        },
                        new
                        {
                            ExpenseId = 1349,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "12 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1809)
                        },
                        new
                        {
                            ExpenseId = 1350,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "13 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1924)
                        },
                        new
                        {
                            ExpenseId = 1351,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "14 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(1986)
                        },
                        new
                        {
                            ExpenseId = 1352,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "15 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2035)
                        },
                        new
                        {
                            ExpenseId = 1353,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "16 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2077)
                        },
                        new
                        {
                            ExpenseId = 1354,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "17 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2124)
                        },
                        new
                        {
                            ExpenseId = 1355,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "18 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2172)
                        },
                        new
                        {
                            ExpenseId = 1356,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "19 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2212)
                        },
                        new
                        {
                            ExpenseId = 1357,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "20 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2253)
                        },
                        new
                        {
                            ExpenseId = 1358,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "21 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2292)
                        },
                        new
                        {
                            ExpenseId = 1359,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "22 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2332)
                        },
                        new
                        {
                            ExpenseId = 1360,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "23 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2372)
                        },
                        new
                        {
                            ExpenseId = 1361,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "24 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2412)
                        },
                        new
                        {
                            ExpenseId = 1362,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "25 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2451)
                        },
                        new
                        {
                            ExpenseId = 1363,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "26 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2492)
                        },
                        new
                        {
                            ExpenseId = 1364,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "27 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2534)
                        },
                        new
                        {
                            ExpenseId = 1365,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "28 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2625)
                        },
                        new
                        {
                            ExpenseId = 1366,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "29 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2677)
                        },
                        new
                        {
                            ExpenseId = 1367,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "30 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2718)
                        },
                        new
                        {
                            ExpenseId = 1368,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "31 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2758)
                        },
                        new
                        {
                            ExpenseId = 1369,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "32 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2797)
                        },
                        new
                        {
                            ExpenseId = 1370,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "33 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2840)
                        },
                        new
                        {
                            ExpenseId = 1371,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "34 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2878)
                        },
                        new
                        {
                            ExpenseId = 1372,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "35 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2917)
                        },
                        new
                        {
                            ExpenseId = 1373,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "36 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2955)
                        },
                        new
                        {
                            ExpenseId = 1374,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "37 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(2992)
                        },
                        new
                        {
                            ExpenseId = 1375,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "38 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3029)
                        },
                        new
                        {
                            ExpenseId = 1376,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "39 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3066)
                        },
                        new
                        {
                            ExpenseId = 1377,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "40 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3104)
                        },
                        new
                        {
                            ExpenseId = 1378,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "41 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3141)
                        },
                        new
                        {
                            ExpenseId = 1379,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "42 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3224)
                        },
                        new
                        {
                            ExpenseId = 1380,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "43 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3274)
                        },
                        new
                        {
                            ExpenseId = 1381,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "44 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3314)
                        },
                        new
                        {
                            ExpenseId = 1382,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "45 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3352)
                        },
                        new
                        {
                            ExpenseId = 1383,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "46 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3389)
                        },
                        new
                        {
                            ExpenseId = 1384,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "47 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3426)
                        },
                        new
                        {
                            ExpenseId = 1385,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "48 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3463)
                        },
                        new
                        {
                            ExpenseId = 1386,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "49 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3500)
                        },
                        new
                        {
                            ExpenseId = 1387,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "50 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3537)
                        },
                        new
                        {
                            ExpenseId = 1388,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "51 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3574)
                        },
                        new
                        {
                            ExpenseId = 1389,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "52 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3611)
                        },
                        new
                        {
                            ExpenseId = 1390,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "53 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3648)
                        },
                        new
                        {
                            ExpenseId = 1391,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "54 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3686)
                        },
                        new
                        {
                            ExpenseId = 1392,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "55 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3723)
                        },
                        new
                        {
                            ExpenseId = 1393,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "56 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3760)
                        },
                        new
                        {
                            ExpenseId = 1394,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "57 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3797)
                        },
                        new
                        {
                            ExpenseId = 1395,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "58 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(3986)
                        },
                        new
                        {
                            ExpenseId = 1396,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "59 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4030)
                        },
                        new
                        {
                            ExpenseId = 1397,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "60 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4069)
                        },
                        new
                        {
                            ExpenseId = 1398,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "61 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4108)
                        },
                        new
                        {
                            ExpenseId = 1399,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "62 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4146)
                        },
                        new
                        {
                            ExpenseId = 1400,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "63 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4184)
                        },
                        new
                        {
                            ExpenseId = 1401,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "64 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4222)
                        },
                        new
                        {
                            ExpenseId = 1402,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "65 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4265)
                        },
                        new
                        {
                            ExpenseId = 1403,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "66 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4304)
                        },
                        new
                        {
                            ExpenseId = 1404,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "67 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4341)
                        },
                        new
                        {
                            ExpenseId = 1405,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "68 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4379)
                        },
                        new
                        {
                            ExpenseId = 1406,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "69 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4417)
                        },
                        new
                        {
                            ExpenseId = 1407,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "70 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4455)
                        },
                        new
                        {
                            ExpenseId = 1408,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "71 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4551)
                        },
                        new
                        {
                            ExpenseId = 1409,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "72 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4593)
                        },
                        new
                        {
                            ExpenseId = 1410,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "73 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4632)
                        },
                        new
                        {
                            ExpenseId = 1411,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "74 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4670)
                        },
                        new
                        {
                            ExpenseId = 1412,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "75 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4708)
                        },
                        new
                        {
                            ExpenseId = 1413,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "76 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4746)
                        },
                        new
                        {
                            ExpenseId = 1414,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "77 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4783)
                        },
                        new
                        {
                            ExpenseId = 1415,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "78 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4821)
                        },
                        new
                        {
                            ExpenseId = 1416,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "79 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4858)
                        },
                        new
                        {
                            ExpenseId = 1417,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "80 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4896)
                        },
                        new
                        {
                            ExpenseId = 1418,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "81 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4934)
                        },
                        new
                        {
                            ExpenseId = 1419,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "82 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(4971)
                        },
                        new
                        {
                            ExpenseId = 1420,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "83 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5008)
                        },
                        new
                        {
                            ExpenseId = 1421,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "84 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5045)
                        },
                        new
                        {
                            ExpenseId = 1422,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "85 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5083)
                        },
                        new
                        {
                            ExpenseId = 1423,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "86 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5172)
                        },
                        new
                        {
                            ExpenseId = 1424,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "87 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5220)
                        },
                        new
                        {
                            ExpenseId = 1425,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "88 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5260)
                        },
                        new
                        {
                            ExpenseId = 1426,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "89 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5298)
                        },
                        new
                        {
                            ExpenseId = 1427,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "90 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5337)
                        },
                        new
                        {
                            ExpenseId = 1428,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "91 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5374)
                        },
                        new
                        {
                            ExpenseId = 1429,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "92 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5412)
                        },
                        new
                        {
                            ExpenseId = 1430,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "93 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5449)
                        },
                        new
                        {
                            ExpenseId = 1431,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "94 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5487)
                        },
                        new
                        {
                            ExpenseId = 1432,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "95 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5524)
                        },
                        new
                        {
                            ExpenseId = 1433,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "96 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5561)
                        },
                        new
                        {
                            ExpenseId = 1434,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "97 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5598)
                        },
                        new
                        {
                            ExpenseId = 1435,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "98 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5635)
                        },
                        new
                        {
                            ExpenseId = 1436,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "99 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5672)
                        },
                        new
                        {
                            ExpenseId = 1437,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "100 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5709)
                        },
                        new
                        {
                            ExpenseId = 1438,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "101 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5894)
                        },
                        new
                        {
                            ExpenseId = 1439,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "102 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(5962)
                        },
                        new
                        {
                            ExpenseId = 1440,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "103 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6003)
                        },
                        new
                        {
                            ExpenseId = 1441,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "104 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6041)
                        },
                        new
                        {
                            ExpenseId = 1442,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "105 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6079)
                        },
                        new
                        {
                            ExpenseId = 1443,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "106 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6117)
                        },
                        new
                        {
                            ExpenseId = 1444,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "107 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6155)
                        },
                        new
                        {
                            ExpenseId = 1445,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "108 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6192)
                        },
                        new
                        {
                            ExpenseId = 1446,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "109 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6230)
                        },
                        new
                        {
                            ExpenseId = 1447,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "110 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6268)
                        },
                        new
                        {
                            ExpenseId = 1448,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "111 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6306)
                        },
                        new
                        {
                            ExpenseId = 1449,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "112 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6344)
                        },
                        new
                        {
                            ExpenseId = 1450,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "113 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6382)
                        },
                        new
                        {
                            ExpenseId = 1451,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "114 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6420)
                        },
                        new
                        {
                            ExpenseId = 1452,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "115 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6458)
                        },
                        new
                        {
                            ExpenseId = 1453,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "116 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6495)
                        },
                        new
                        {
                            ExpenseId = 1454,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "117 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6594)
                        },
                        new
                        {
                            ExpenseId = 1455,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "118 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6636)
                        },
                        new
                        {
                            ExpenseId = 1456,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "119 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6674)
                        },
                        new
                        {
                            ExpenseId = 1457,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "120 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6712)
                        },
                        new
                        {
                            ExpenseId = 1458,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "121 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6750)
                        },
                        new
                        {
                            ExpenseId = 1459,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "122 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6788)
                        },
                        new
                        {
                            ExpenseId = 1460,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "123 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6826)
                        },
                        new
                        {
                            ExpenseId = 1461,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "124 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6864)
                        },
                        new
                        {
                            ExpenseId = 1462,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "125 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6902)
                        },
                        new
                        {
                            ExpenseId = 1463,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "126 automatically added expense",
                            Date = new DateTime(2021, 3, 16, 16, 53, 50, 999, DateTimeKind.Local).AddTicks(6939)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.Category", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.Expense", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Expenses")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("BudgetPlanner2Web.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.ApplicationUser", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
