// <auto-generated />
using System;
using BudgetPlanner2Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BudgetPlanner2Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210318011501_CreatedUpdatedNullable")]
    partial class CreatedUpdatedNullable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BudgetPlanner2Web.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1337,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "0 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 259, DateTimeKind.Local).AddTicks(480)
                        },
                        new
                        {
                            Id = 1338,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "1 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2251)
                        },
                        new
                        {
                            Id = 1339,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "2 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2496)
                        },
                        new
                        {
                            Id = 1340,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "3 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2550)
                        },
                        new
                        {
                            Id = 1341,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "4 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2592)
                        },
                        new
                        {
                            Id = 1342,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "5 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2644)
                        },
                        new
                        {
                            Id = 1343,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "6 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2685)
                        },
                        new
                        {
                            Id = 1344,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "7 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2746)
                        },
                        new
                        {
                            Id = 1345,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "8 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2789)
                        },
                        new
                        {
                            Id = 1346,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "9 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2832)
                        },
                        new
                        {
                            Id = 1347,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "10 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2871)
                        },
                        new
                        {
                            Id = 1348,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "11 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2911)
                        },
                        new
                        {
                            Id = 1349,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "12 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2949)
                        },
                        new
                        {
                            Id = 1350,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "13 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(2986)
                        },
                        new
                        {
                            Id = 1351,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "14 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3024)
                        },
                        new
                        {
                            Id = 1352,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "15 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3061)
                        },
                        new
                        {
                            Id = 1353,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "16 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3099)
                        },
                        new
                        {
                            Id = 1354,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "17 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3140)
                        },
                        new
                        {
                            Id = 1355,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "18 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3178)
                        },
                        new
                        {
                            Id = 1356,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "19 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3217)
                        },
                        new
                        {
                            Id = 1357,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "20 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3264)
                        },
                        new
                        {
                            Id = 1358,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "21 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3306)
                        },
                        new
                        {
                            Id = 1359,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "22 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3344)
                        },
                        new
                        {
                            Id = 1360,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "23 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3382)
                        },
                        new
                        {
                            Id = 1361,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "24 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3420)
                        },
                        new
                        {
                            Id = 1362,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "25 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3457)
                        },
                        new
                        {
                            Id = 1363,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "26 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3495)
                        },
                        new
                        {
                            Id = 1364,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "27 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3532)
                        },
                        new
                        {
                            Id = 1365,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "28 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3569)
                        },
                        new
                        {
                            Id = 1366,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "29 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3606)
                        },
                        new
                        {
                            Id = 1367,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "30 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3643)
                        },
                        new
                        {
                            Id = 1368,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "31 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3680)
                        },
                        new
                        {
                            Id = 1369,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "32 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3717)
                        },
                        new
                        {
                            Id = 1370,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "33 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3757)
                        },
                        new
                        {
                            Id = 1371,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "34 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3805)
                        },
                        new
                        {
                            Id = 1372,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "35 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3845)
                        },
                        new
                        {
                            Id = 1373,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "36 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3883)
                        },
                        new
                        {
                            Id = 1374,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "37 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3921)
                        },
                        new
                        {
                            Id = 1375,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "38 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(3960)
                        },
                        new
                        {
                            Id = 1376,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "39 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4035)
                        },
                        new
                        {
                            Id = 1377,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "40 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4080)
                        },
                        new
                        {
                            Id = 1378,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "41 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4119)
                        },
                        new
                        {
                            Id = 1379,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "42 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4158)
                        },
                        new
                        {
                            Id = 1380,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "43 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4197)
                        },
                        new
                        {
                            Id = 1381,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "44 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4235)
                        },
                        new
                        {
                            Id = 1382,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "45 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4273)
                        },
                        new
                        {
                            Id = 1383,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "46 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4311)
                        },
                        new
                        {
                            Id = 1384,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "47 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4348)
                        },
                        new
                        {
                            Id = 1385,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "48 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4396)
                        },
                        new
                        {
                            Id = 1386,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "49 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4437)
                        },
                        new
                        {
                            Id = 1387,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "50 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4475)
                        },
                        new
                        {
                            Id = 1388,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "51 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4513)
                        },
                        new
                        {
                            Id = 1389,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "52 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4550)
                        },
                        new
                        {
                            Id = 1390,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "53 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4588)
                        },
                        new
                        {
                            Id = 1391,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "54 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4625)
                        },
                        new
                        {
                            Id = 1392,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "55 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4663)
                        },
                        new
                        {
                            Id = 1393,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "56 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4701)
                        },
                        new
                        {
                            Id = 1394,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "57 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4738)
                        },
                        new
                        {
                            Id = 1395,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "58 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4776)
                        },
                        new
                        {
                            Id = 1396,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "59 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4813)
                        },
                        new
                        {
                            Id = 1397,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "60 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4851)
                        },
                        new
                        {
                            Id = 1398,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "61 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4888)
                        },
                        new
                        {
                            Id = 1399,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "62 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4935)
                        },
                        new
                        {
                            Id = 1400,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "63 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(4977)
                        },
                        new
                        {
                            Id = 1401,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "64 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5017)
                        },
                        new
                        {
                            Id = 1402,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "65 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5059)
                        },
                        new
                        {
                            Id = 1403,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "66 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5097)
                        },
                        new
                        {
                            Id = 1404,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "67 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5135)
                        },
                        new
                        {
                            Id = 1405,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "68 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5173)
                        },
                        new
                        {
                            Id = 1406,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "69 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5211)
                        },
                        new
                        {
                            Id = 1407,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "70 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5248)
                        },
                        new
                        {
                            Id = 1408,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "71 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5285)
                        },
                        new
                        {
                            Id = 1409,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "72 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5322)
                        },
                        new
                        {
                            Id = 1410,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "73 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5359)
                        },
                        new
                        {
                            Id = 1411,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "74 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5404)
                        },
                        new
                        {
                            Id = 1412,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "75 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5443)
                        },
                        new
                        {
                            Id = 1413,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "76 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5481)
                        },
                        new
                        {
                            Id = 1414,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "77 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5518)
                        },
                        new
                        {
                            Id = 1415,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "78 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5556)
                        },
                        new
                        {
                            Id = 1416,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "79 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5595)
                        },
                        new
                        {
                            Id = 1417,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "80 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5633)
                        },
                        new
                        {
                            Id = 1418,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "81 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5670)
                        },
                        new
                        {
                            Id = 1419,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "82 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5708)
                        },
                        new
                        {
                            Id = 1420,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "83 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5745)
                        },
                        new
                        {
                            Id = 1421,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "84 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5783)
                        },
                        new
                        {
                            Id = 1422,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "85 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5820)
                        },
                        new
                        {
                            Id = 1423,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "86 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5858)
                        },
                        new
                        {
                            Id = 1424,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "87 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5895)
                        },
                        new
                        {
                            Id = 1425,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "88 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5932)
                        },
                        new
                        {
                            Id = 1426,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "89 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(5985)
                        },
                        new
                        {
                            Id = 1427,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "90 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6024)
                        },
                        new
                        {
                            Id = 1428,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "91 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6061)
                        },
                        new
                        {
                            Id = 1429,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "92 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6098)
                        },
                        new
                        {
                            Id = 1430,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "93 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6136)
                        },
                        new
                        {
                            Id = 1431,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "94 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6172)
                        },
                        new
                        {
                            Id = 1432,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "95 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6209)
                        },
                        new
                        {
                            Id = 1433,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "96 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6246)
                        },
                        new
                        {
                            Id = 1434,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "97 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6284)
                        },
                        new
                        {
                            Id = 1435,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "98 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6322)
                        },
                        new
                        {
                            Id = 1436,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "99 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6359)
                        },
                        new
                        {
                            Id = 1437,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "100 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6396)
                        },
                        new
                        {
                            Id = 1438,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "101 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6434)
                        },
                        new
                        {
                            Id = 1439,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "102 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6471)
                        },
                        new
                        {
                            Id = 1440,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "103 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6517)
                        },
                        new
                        {
                            Id = 1441,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "104 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6557)
                        },
                        new
                        {
                            Id = 1442,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "105 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6594)
                        },
                        new
                        {
                            Id = 1443,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "106 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6632)
                        },
                        new
                        {
                            Id = 1444,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "107 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6670)
                        },
                        new
                        {
                            Id = 1445,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "108 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6707)
                        },
                        new
                        {
                            Id = 1446,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "109 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6745)
                        },
                        new
                        {
                            Id = 1447,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "110 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6782)
                        },
                        new
                        {
                            Id = 1448,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "111 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6818)
                        },
                        new
                        {
                            Id = 1449,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "112 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6855)
                        },
                        new
                        {
                            Id = 1450,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "113 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6892)
                        },
                        new
                        {
                            Id = 1451,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "114 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6929)
                        },
                        new
                        {
                            Id = 1452,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "115 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(6966)
                        },
                        new
                        {
                            Id = 1453,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "116 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7003)
                        },
                        new
                        {
                            Id = 1454,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "117 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7184)
                        },
                        new
                        {
                            Id = 1455,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "118 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7242)
                        },
                        new
                        {
                            Id = 1456,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "119 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7283)
                        },
                        new
                        {
                            Id = 1457,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "120 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7322)
                        },
                        new
                        {
                            Id = 1458,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "121 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7361)
                        },
                        new
                        {
                            Id = 1459,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "122 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7401)
                        },
                        new
                        {
                            Id = 1460,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "123 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7440)
                        },
                        new
                        {
                            Id = 1461,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "124 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7479)
                        },
                        new
                        {
                            Id = 1462,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "125 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7518)
                        },
                        new
                        {
                            Id = 1463,
                            Amount = 13.37m,
                            ApplicationUserId = "9659f3cc-8531-4b6b-bba3-382c108b192c",
                            CategoryId = 16,
                            Comment = "126 automatically added expense",
                            Date = new DateTime(2021, 3, 18, 3, 15, 0, 265, DateTimeKind.Local).AddTicks(7557)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.Category", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.Expense", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("Expenses")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("BudgetPlanner2Web.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BudgetPlanner2Web.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetPlanner2Web.Models.ApplicationUser", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
